import { AppointmentRecord } from '../types/appointment'

export const APPOINTMENT_DATA: AppointmentRecord[] = [
  // Cardiology - أمراض القلب
  { 
    id: '1', 
    doctorName: 'د. أحمد العمري', 
    specialization: 'Cardiology', 
    hospital: 'مشفى الأسد الجامعي', 
    city: 'دمشق', 
    appointmentDate: '2024-01-15', 
    appointmentTime: '09:00', 
    patientAge: '46-55', 
    patientGender: 'ذكر', 
    status: 'مكتمل', 
    fee: 50000, 
    duration: 30, 
    paymentStatus: 'مدفوع', 
    appointmentType: 'كشف جديد',
    patientName: 'محمد علي',
    phoneNumber: '0991234567'
  },
  { 
    id: '2', 
    doctorName: 'د. أحمد العمري', 
    specialization: 'Cardiology', 
    hospital: 'مشفى الأسد الجامعي', 
    city: 'دمشق', 
    appointmentDate: '2024-01-15', 
    appointmentTime: '09:30', 
    patientAge: '56+', 
    patientGender: 'أنثى', 
    status: 'مكتمل', 
    fee: 45000, 
    duration: 45, 
    paymentStatus: 'مدفوع', 
    appointmentType: 'متابعة',
    patientName: 'فاطمة حسن',
    phoneNumber: '0947654321'
  },
  { 
    id: '3', 
    doctorName: 'د. محمد الحلبي', 
    specialization: 'Cardiology', 
    hospital: 'مشفى حلب الجامعي', 
    city: 'حلب', 
    appointmentDate: '2024-01-16', 
    appointmentTime: '10:00', 
    patientAge: '36-45', 
    patientGender: 'ذكر', 
    status: 'مكتمل', 
    fee: 40000, 
    duration: 25, 
    paymentStatus: 'مدفوع', 
    appointmentType: 'كشف جديد',
    patientName: 'عمر خالد',
    phoneNumber: '0931234567'
  },

  // Dermatology - أمراض الجلد
  { 
    id: '4', 
    doctorName: 'د. سارة القادري', 
    specialization: 'Dermatology', 
    hospital: 'مشفى المواساة', 
    city: 'حمص', 
    appointmentDate: '2024-01-17', 
    appointmentTime: '11:00', 
    patientAge: '18-25', 
    patientGender: 'أنثى', 
    status: 'مكتمل', 
    fee: 35000, 
    duration: 20, 
    paymentStatus: 'مدفوع', 
    appointmentType: 'كشف جديد',
    patientName: 'سلمى محمد',
    phoneNumber: '0981234567'
  },
  { 
    id: '5', 
    doctorName: 'د. علي الساحلي', 
    specialization: 'Dermatology', 
    hospital: 'مشفى تشرين', 
    city: 'اللاذقية', 
    appointmentDate: '2024-01-18', 
    appointmentTime: '14:00', 
    patientAge: '26-35', 
    patientGender: 'ذكر', 
    status: 'مكتمل', 
    fee: 30000, 
    duration: 30, 
    paymentStatus: 'مدفوع', 
    appointmentType: 'متابعة',
    patientName: 'ياسين محمود',
    phoneNumber: '0951234567'
  },

  // Endocrinology - الغدد الصماء
  { 
    id: '6', 
    doctorName: 'د. فاطمة النجار', 
    specialization: 'Endocrinology', 
    hospital: 'مشفى الأسد الجامعي', 
    city: 'دمشق', 
    appointmentDate: '2024-01-19', 
    appointmentTime: '08:30', 
    patientAge: '36-45', 
    patientGender: 'أنثى', 
    status: 'مكتمل', 
    fee: 55000, 
    duration: 40, 
    paymentStatus: 'مدفوع', 
    appointmentType: 'كشف جديد',
    patientName: 'هدى أحمد',
    phoneNumber: '0961234567'
  },
  { 
    id: '7', 
    doctorName: 'د. ياسر الشامي', 
    specialization: 'Endocrinology', 
    hospital: 'مشفى حلب الجامعي', 
    city: 'حلب', 
    appointmentDate: '2024-01-20', 
    appointmentTime: '15:00', 
    patientAge: '46-55', 
    patientGender: 'ذكر', 
    status: 'مؤجل', 
    fee: 48000, 
    duration: 35, 
    paymentStatus: 'غير مدفوع', 
    appointmentType: 'متابعة',
    patientName: 'خالد إبراهيم',
    phoneNumber: '0971234567'
  },

  // Gastroenterology - الجهاز الهضمي
  { 
    id: '8', 
    doctorName: 'د. حسن درويش', 
    specialization: 'Gastroenterology', 
    hospital: 'مشفى الوطني', 
    city: 'درعا', 
    appointmentDate: '2024-01-21', 
    appointmentTime: '10:30', 
    patientAge: '26-35', 
    patientGender: 'ذكر', 
    status: 'مكتمل', 
    fee: 42000, 
    duration: 25, 
    paymentStatus: 'مدفوع', 
    appointmentType: 'كشف جديد',
    patientName: 'محمود سعيد',
    phoneNumber: '0921234567'
  },
  { 
    id: '9', 
    doctorName: 'د. لينا الصفدي', 
    specialization: 'Gastroenterology', 
    hospital: 'مشفى البعث', 
    city: 'حمص', 
    appointmentDate: '2024-01-22', 
    appointmentTime: '13:00', 
    patientAge: '56+', 
    patientGender: 'أنثى', 
    status: 'قيد الانتظار', 
    fee: 46000, 
    duration: 30, 
    paymentStatus: 'غير مدفوع', 
    appointmentType: 'استشارة',
    patientName: 'نورا عبدالله',
    phoneNumber: '0911234567'
  },

  // Neurology - الأعصاب
  { 
    id: '10', 
    doctorName: 'د. نبيل عثمان', 
    specialization: 'Neurology', 
    hospital: 'مشفى الأسد الجامعي', 
    city: 'دمشق', 
    appointmentDate: '2024-01-23', 
    appointmentTime: '09:15', 
    patientAge: '56+', 
    patientGender: 'أنثى', 
    status: 'مكتمل', 
    fee: 60000, 
    duration: 45, 
    paymentStatus: 'مدفوع', 
    appointmentType: 'متابعة',
    patientName: 'عفاف عمر',
    phoneNumber: '0901234567'
  },

  // المزيد من البيانات...
  { 
    id: '11', 
    doctorName: 'د. هدى الحمصي', 
    specialization: 'Neurology', 
    hospital: 'مشفى حلب الجامعي', 
    city: 'حلب', 
    appointmentDate: '2024-01-24', 
    appointmentTime: '11:30', 
    patientAge: '36-45', 
    patientGender: 'أنثى', 
    status: 'مكتمل', 
    fee: 52000, 
    duration: 35, 
    paymentStatus: 'مدفوع', 
    appointmentType: 'كشف جديد',
    patientName: 'ريماس خليل',
    phoneNumber: '0891234567'
  },
  { 
    id: '12', 
    doctorName: 'د. وائل قدورة', 
    specialization: 'Pulmonology', 
    hospital: 'مشفى البعث', 
    city: 'حمص', 
    appointmentDate: '2024-01-25', 
    appointmentTime: '08:45', 
    patientAge: '18-25', 
    patientGender: 'ذكر', 
    status: 'مكتمل', 
    fee: 38000, 
    duration: 20, 
    paymentStatus: 'مدفوع', 
    appointmentType: 'كشف جديد',
    patientName: 'باسل ناصر',
    phoneNumber: '0881234567'
  },
  { 
    id: '13', 
    doctorName: 'د. باسل البحري', 
    specialization: 'Pulmonology', 
    hospital: 'مشفى تشرين', 
    city: 'اللاذقية', 
    appointmentDate: '2024-01-26', 
    appointmentTime: '16:00', 
    patientAge: '56+', 
    patientGender: 'ذكر', 
    status: 'ملغي', 
    fee: 44000, 
    duration: 40, 
    paymentStatus: 'غير مدفوع', 
    appointmentType: 'طوارئ',
    patientName: 'سمير حافظ',
    phoneNumber: '0871234567'
  },
  { 
    id: '14', 
    doctorName: 'د. رياض قاسم', 
    specialization: 'Orthopedics', 
    hospital: 'مشفى الوطني', 
    city: 'درعا', 
    appointmentDate: '2024-01-27', 
    appointmentTime: '14:30', 
    patientAge: '46-55', 
    patientGender: 'أنثى', 
    status: 'مكتمل', 
    fee: 48000, 
    duration: 30, 
    paymentStatus: 'مدفوع', 
    appointmentType: 'متابعة',
    patientName: 'لمى فارس',
    phoneNumber: '0861234567'
  },
  { 
    id: '15', 
    doctorName: 'د. مازن الشافعي', 
    specialization: 'Orthopedics', 
    hospital: 'مشفى الأسد الجامعي', 
    city: 'دمشق', 
    appointmentDate: '2024-01-28', 
    appointmentTime: '10:15', 
    patientAge: '26-35', 
    patientGender: 'ذكر', 
    status: 'مكتمل', 
    fee: 42000, 
    duration: 25, 
    paymentStatus: 'مدفوع', 
    appointmentType: 'كشف جديد',
    patientName: 'قصي محمد',
    phoneNumber: '0851234567'
  },
  { 
    id: '16', 
    doctorName: 'د. منى الحلبي', 
    specialization: 'Pediatrics', 
    hospital: 'مشفى حلب الجامعي', 
    city: 'حلب', 
    appointmentDate: '2024-01-29', 
    appointmentTime: '09:45', 
    patientAge: '0-17', 
    patientGender: 'ذكر', 
    status: 'مكتمل', 
    fee: 35000, 
    duration: 20, 
    paymentStatus: 'مدفوع', 
    appointmentType: 'كشف جديد',
    patientName: 'عمران كمال',
    phoneNumber: '0841234567'
  },
  { 
    id: '17', 
    doctorName: 'د. إيمان حمصي', 
    specialization: 'Pediatrics', 
    hospital: 'مشفى البعث', 
    city: 'حمص', 
    appointmentDate: '2024-01-30', 
    appointmentTime: '11:15', 
    patientAge: '0-17', 
    patientGender: 'أنثى', 
    status: 'مكتمل', 
    fee: 32000, 
    duration: 15, 
    paymentStatus: 'مدفوع', 
    appointmentType: 'متابعة',
    patientName: 'جنى أحمد',
    phoneNumber: '0831234567'
  },
  { 
    id: '18', 
    doctorName: 'د. خالد ساحلي', 
    specialization: 'Ophthalmology', 
    hospital: 'مشفى تشرين', 
    city: 'اللاذقية', 
    appointmentDate: '2024-01-31', 
    appointmentTime: '13:30', 
    patientAge: '56+', 
    patientGender: 'أنثى', 
    status: 'مكتمل', 
    fee: 52000, 
    duration: 35, 
    paymentStatus: 'مدفوع', 
    appointmentType: 'كشف جديد',
    patientName: 'وفاء سالم',
    phoneNumber: '0821234567'
  },
  { 
    id: '19', 
    doctorName: 'د. ناديا دمشقية', 
    specialization: 'Ophthalmology', 
    hospital: 'مشفى الأسد الجامعي', 
    city: 'دمشق', 
    appointmentDate: '2024-02-01', 
    appointmentTime: '15:45', 
    patientAge: '36-45', 
    patientGender: 'ذكر', 
    status: 'قيد الانتظار', 
    fee: 48000, 
    duration: 30, 
    paymentStatus: 'غير مدفوع', 
    appointmentType: 'استشارة',
    patientName: 'عماد توفيق',
    phoneNumber: '0811234567'
  },
  { 
    id: '20', 
    doctorName: 'د. معن حلاق', 
    specialization: 'Psychiatry', 
    hospital: 'مشفى حلب الجامعي', 
    city: 'حلب', 
    appointmentDate: '2024-02-02', 
    appointmentTime: '10:00', 
    patientAge: '26-35', 
    patientGender: 'أنثى', 
    status: 'مكتمل', 
    fee: 45000, 
    duration: 50, 
    paymentStatus: 'مدفوع', 
    appointmentType: 'كشف جديد',
    patientName: 'سارة محسن',
    phoneNumber: '0801234567'
  },
  // ... استمرار البيانات لنحو 50 سجل
]

export const DOCTORS = [
  { value: 'all', label: 'جميع الأطباء' },
  { value: 'د. أحمد العمري', label: 'د. أحمد العمري' },
  { value: 'د. محمد الحلبي', label: 'د. محمد الحلبي' },
  { value: 'د. سارة القادري', label: 'د. سارة القادري' },
  { value: 'د. علي الساحلي', label: 'د. علي الساحلي' },
  { value: 'د. فاطمة النجار', label: 'د. فاطمة النجار' },
  { value: 'د. ياسر الشامي', label: 'د. ياسر الشامي' },
  { value: 'د. حسن درويش', label: 'د. حسن درويش' },
  { value: 'د. لينا الصفدي', label: 'د. لينا الصفدي' },
  { value: 'د. نبيل عثمان', label: 'د. نبيل عثمان' },
  { value: 'د. هدى الحمصي', label: 'د. هدى الحمصي' },
  { value: 'د. وائل قدورة', label: 'د. وائل قدورة' },
  { value: 'د. باسل البحري', label: 'د. باسل البحري' },
  { value: 'د. رياض قاسم', label: 'د. رياض قاسم' },
  { value: 'د. مازن الشافعي', label: 'د. مازن الشافعي' },
  { value: 'د. منى الحلبي', label: 'د. منى الحلبي' },
  { value: 'د. إيمان حمصي', label: 'د. إيمان حمصي' },
  { value: 'د. خالد ساحلي', label: 'د. خالد ساحلي' },
  { value: 'د. ناديا دمشقية', label: 'د. ناديا دمشقية' },
  { value: 'د. معن حلاق', label: 'د. معن حلاق' },
  { value: 'د. ريم دمشقية', label: 'د. ريم دمشقية' },
]

export const SPECIALIZATIONS = [
  { value: 'all', label: 'جميع التخصصات' },
  { value: 'Cardiology', label: 'أمراض القلب' },
  { value: 'Dermatology', label: 'الأمراض الجلدية' },
  { value: 'Endocrinology', label: 'الغدد الصماء' },
  { value: 'Gastroenterology', label: 'الجهاز الهضمي' },
  { value: 'Neurology', label: 'الأمراض العصبية' },
  { value: 'Pulmonology', label: 'أمراض الرئة' },
  { value: 'Orthopedics', label: 'العظام' },
  { value: 'Pediatrics', label: 'طب الأطفال' },
  { value: 'Ophthalmology', label: 'العيون' },
  { value: 'Psychiatry', label: 'الطب النفسي' },
  { value: 'Surgery', label: 'الجراحة' },
  { value: 'Urology', label: 'مسالك بولية' },
  { value: 'Oncology', label: 'الأورام' },
]

export const HOSPITALS = [
  { value: 'all', label: 'جميع المستشفيات' },
  { value: 'مشفى الأسد الجامعي', label: 'مشفى الأسد الجامعي' },
  { value: 'مشفى حلب الجامعي', label: 'مشفى حلب الجامعي' },
  { value: 'مشفى المواساة', label: 'مشفى المواساة' },
  { value: 'مشفى تشرين', label: 'مشفى تشرين' },
  { value: 'مشفى الوطني', label: 'مشفى الوطني' },
  { value: 'مشفى البعث', label: 'مشفى البعث' },
  { value: 'مشفى الأطفال', label: 'مشفى الأطفال' },
  { value: 'مشفى المواساة الإسلامي', label: 'مشفى المواساة الإسلامي' },
]

export const CITIES = [
  { value: 'all', label: 'جميع المدن' },
  { value: 'دمشق', label: 'دمشق' },
  { value: 'حلب', label: 'حلب' },
  { value: 'حمص', label: 'حمص' },
  { value: 'اللاذقية', label: 'اللاذقية' },
  { value: 'درعا', label: 'درعا' },
  { value: 'حماة', label: 'حماة' },
  { value: 'طرطوس', label: 'طرطوس' },
  { value: 'السويداء', label: 'السويداء' },
]

export const STATUS_TYPES = [
  { value: 'all', label: 'جميع الحالات' },
  { value: 'مكتمل', label: 'مكتمل' },
  { value: 'ملغي', label: 'ملغي' },
  { value: 'مؤجل', label: 'مؤجل' },
  { value: 'قيد الانتظار', label: 'قيد الانتظار' },
]

export const PAYMENT_STATUS = [
  { value: 'all', label: 'جميع حالات الدفع' },
  { value: 'مدفوع', label: 'مدفوع' },
  { value: 'غير مدفوع', label: 'غير مدفوع' },
  { value: 'جزئي', label: 'جزئي' },
]

export const APPOINTMENT_TYPES = [
  { value: 'all', label: 'جميع أنواع المواعيد' },
  { value: 'كشف جديد', label: 'كشف جديد' },
  { value: 'متابعة', label: 'متابعة' },
  { value: 'طوارئ', label: 'طوارئ' },
  { value: 'استشارة', label: 'استشارة' },
]

export const GENDERS = [
  { value: 'all', label: 'جميع الجنسين' },
  { value: 'ذكر', label: 'ذكر' },
  { value: 'أنثى', label: 'أنثى' },
]

export const DATE_RANGES = [
  { value: 'all', label: 'جميع الفترات' },
  { value: '2024-01', label: 'يناير 2024' },
  { value: '2024-02', label: 'فبراير 2024' },
  { value: '2024-03', label: 'مارس 2024' },
  { value: '2023-12', label: 'ديسمبر 2023' },
  { value: '2023-11', label: 'نوفمبر 2023' },
]

export const CHART_COLORS = [
  '#0088FE', '#00C49F', '#FFBB28', '#FF8042', '#8884D8',
  '#82CA9D', '#FFC658', '#8DD1E1', '#D084C9', '#F95F62',
  '#A4DE6C', '#D0ED57', '#FFA500', '#87CEEB', '#DA70D6',
  '#32CD32', '#BA55D3', '#9370DB', '#3CB371', '#B22222'
]